### ISSUE TITLE
calc_clim error 

### ISSUE THREAD

**Issue by florianboergel** [steidani/ConTrack#2]
Hey,

when using block.calc_anom() with a different 'groupby' option than 'dayofyear' calc_clim() returns an error.

I think this is because calc_clim() uses in step #2  'dayofyear' as a fixed dimension.
```python
clim = clim.rolling(dayofyear=window, center=True).mean().fillna(
            clim[-window:].mean(dim=groupby)   
```

I think this can be solved by renaming the dimension first.

```python
    clim = clim.rename({groupby: "window_dim"})
    clim = clim.rolling(window_dim=window, center=True).mean().fillna(
        clim[-window:].mean(dim="window_dim"))
```

However, there might be a better solution for this. 

Best 

Flo

**Comment by steidani** [comment]
Hi Flo,

thank you for spotting the mistake.

Because we need the same name of the time dimension for 'groupby' when calculating the anomaly in step 2 of block.calc_anom(), I changed it to 
```
clim = clim.rolling(**{groupby:window}, center=True).mean().fillna(
            clim[-window:].mean(dim=groupby)    
)
```

Best,
Dani

**Comment by florianboergel** [comment]
Perfect. Thanks for providing this package.
