### ISSUE TITLE
conTrack algorithm : periodic boundary discontinuity

### ISSUE THREAD

**Issue by Vinita-D** [steidani/ConTrack#5]
It seems the issue lies in the continuity of contours near the 180-degree longitude boundary. This can often be problematic due to the discontinuity caused by the Earth's spherical nature in grid-based data. Ensuring continuity across the 180-degree meridian can be complex, especially with periodic data.

**Comment by Vinita-D** [comment]
It seems the issue was already fixed in [8e78d58](https://github.com/steidani/ConTrack/commit/8e78d588fba570a43c2b1b12f58e84e94782e1dc) but it is not a part of the latest release. So `pip install contrack` installs the bugged version but installing it directly from github works.

**Comment by steidani** [comment]
Hi @vinieeee 
Thanks for spotting the mistake. Yes, best to install ConTrack directly from Github:

.. code:: bash
    pip install git+https://github.com/steidani/ConTrack
